image:
  repository: bondblaze/imdb-ratings
  pullPolicy: Always
  tag: "latest"

resources:
  limits:
    cpu: 100m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 256Mi

pdb:
  enabled: true
  minAvailable: 2

hpa:
  enabled: true
  minReplicas: 4
  maxReplicas: 20
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 70