{{- if .Values.pdb.enabled }}
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ include "imdb-ratings.fullname" . }}
spec:
  minAvailable  : {{ .Values.pdb.minAvailable }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "imdb-ratings.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}