apiVersion: v1
kind: Secret
metadata:
  name: "{{ include "imdb-ratings.fullname" . }}-env"
  labels:
    app.kubernetes.io/name: {{ include "imdb-ratings.name" . }}
    helm.sh/chart: {{ include "imdb-ratings.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
{{ (.Files.Glob "secrets/dotenv.credentials").AsSecrets | indent 2 }}