apiVersion: v1
kind: Service
metadata:
  name: {{ include "imdb-ratings.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "imdb-ratings.name" . }}
    helm.sh/chart: {{ include "imdb-ratings.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
{{- if .Values.service.annotations }}
  annotations:
  {{- range $key, $value := .Values.service.annotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "imdb-ratings.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
