name: 'imdb-ratings-dev'

on:
  push:
    branches:
      - 'main'
env:
  API_KEY: ${{ secrets.API_KEY }}
  NAMESPACE: "development"
  IMAGE_TAG: "latest"
  KUBECONFIG: "/tmp/kubeconfig"

jobs:
  test:
    name: 'test'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Python 3.10.4
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.4
      - name: 'Run Unit Tests'
        working-directory: imdb-ratings
        run: |
           pip install -r requirements.txt && pytest --cov=.