name: 'imdb-ratings-dev'

on:
  push:
    branches:
      - 'main'
env:
  API_KEY: ${{ secrets.API_KEY }}
  NAMESPACE: "development"
  IMAGE_TAG: "latest"
  KUBECONFIG: "/tmp/kubeconfig"

jobs:
  test:
    name: 'test'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.4
      - name: 'Run Unit Tests'
        working-directory: imdb-ratings
        run: |
           pip install -r requirements.txt && pytest --cov=.

  # analyze:
  #   name: 'analyze'
  #   runs-on: ubuntu-latest
  #   permissions:
  #     actions: read
  #     contents: read
  #     security-events: write

  #   strategy:
  #     fail-fast: false
  #     matrix:
  #       language: [ 'python' ]

  #   steps:
  #   - name: Checkout repository
  #     uses: actions/checkout@v3

  #   - name: Initialize CodeQL
  #     uses: github/codeql-action/init@v2
  #     with:
  #       languages: ${{ matrix.language }}

  #   - name: Autobuild
  #     uses: github/codeql-action/autobuild@v2

  #   - name: Perform CodeQL Analysis
  #     uses: github/codeql-action/analyze@v2
  
  build:
    name: 'build'
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ./imdb-ratings
          push: true
          tags: bondblaze/imdb-ratings:${{ env.IMAGE_TAG }}